name: lsst-panel

channels:
    - conda-forge
    - pyviz
    - defaults

dependencies:
    - python>=3.7
    - param
    - panel>=0.6.3
    - holoviews
    - hvplot
    - geoviews
    - numpy
    - pandas
    - dask
    - distributed
    - dask-jobqueue
    - datashader
    - colorcet
    - jupyterlab
    - fastparquet
    - python-snappy
    - pyarrow
    - sphinx
    - scikit-learn
    - nbsite
    - recommonmark
    - sphinx_rtd_theme
    
